apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oathkeeper
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: admin.0x7cd.xyz
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: test-oathkeeper-proxy
            port:
              number: 4455
